using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LuminaSharp.Generators;

/// <summary>
/// Generates the native->managed export registration from <c>[ManagedExport]</c> methods. Every
/// <c>[ManagedExport]</c> (which is also <c>[UnmanagedCallersOnly]</c>) static method is registered, by name,
/// into <c>ManagedExportRegistry</c>; native resolves a managed function pointer by that name at bootstrap
/// (see <c>DotNet::ResolveManagedExport</c>). There is no hand-mirrored C++ struct and no layout/hash to keep
/// in sync, adding a native->C# call is just this attribute. The export name defaults to the method name; a
/// constructor argument overrides it (e.g. <c>[ManagedExport(""MyPlugin.Foo"")]</c>).
///
/// The same attribute works in plugin/game script assemblies. Combined with a <c>[ModuleInitializer]</c> that
/// calls <c>ManagedExportRegistry.Register</c>, a plugin exposes a typed C# function to C++ with no engine
/// changes (see ManagedExportRegistry for the lifetime rules).
/// </summary>
[Generator]
public sealed class ManagedExportGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "LuminaSharp.ManagedExportAttribute";

    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace LuminaSharp
{
    /// <summary>
    /// Marks a static [UnmanagedCallersOnly] method as a native->managed export. The generator registers it,
    /// by name, into ManagedExportRegistry; native resolves it by that name. The name defaults to the method
    /// name; pass a constructor argument to override it.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
    internal sealed class ManagedExportAttribute : global::System.Attribute
    {
        public ManagedExportAttribute() { }
        public ManagedExportAttribute(string name) { Name = name; }
        public string? Name { get; set; }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("ManagedExportAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<Model?> models = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            predicate: static (node, _) => node is MethodDeclarationSyntax,
            transform: static (ctx, ct) => BuildModel(ctx, ct));

        IncrementalValueProvider<ImmutableArray<Model?>> collected = models.Collect();

        context.RegisterSourceOutput(collected, static (spc, all) => Emit(spc, all));
    }

    // ExportName = the name native resolves by (attribute arg, else the method name); Method = the C# method
    // name; ContainingType = e.g. "global::LuminaSharp.Host"; Signature = the delegate* type arguments
    // ("byte*, int, ulong, uint, global::System.IntPtr"), return type last.
    private sealed record Model(string ExportName, string Method, string ContainingType, string Signature);

    private static Model? BuildModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method || !method.IsStatic)
        {
            return null;
        }

        // Export name: the constructor arg / Name property if given, otherwise the method name.
        string exportName = method.Name;
        AttributeData attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is string ctorName && ctorName.Length > 0)
        {
            exportName = ctorName;
        }
        foreach (KeyValuePair<string, TypedConstant> named in attr.NamedArguments)
        {
            if (named.Key == "Name" && named.Value.Value is string n && n.Length > 0)
            {
                exportName = n;
            }
        }

        SymbolDisplayFormat fq = SymbolDisplayFormat.FullyQualifiedFormat;

        var args = new StringBuilder();
        foreach (IParameterSymbol p in method.Parameters)
        {
            args.Append(p.Type.ToDisplayString(fq)).Append(", ");
        }
        // delegate* type arguments end with the return type (void for a void method).
        args.Append(method.ReturnsVoid ? "void" : method.ReturnType.ToDisplayString(fq));

        string containing = method.ContainingType.ToDisplayString(fq);
        return new Model(exportName, method.Name, containing, args.ToString());
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<Model?> all)
    {
        var exports = all
            .Where(m => m is not null)
            .Select(m => m!)
            .GroupBy(m => m.ExportName)
            .Select(g => g.First())             // de-dupe (partial decls etc.)
            .OrderBy(m => m.ExportName, System.StringComparer.Ordinal)
            .ToArray();

        if (exports.Length == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.Append(@"// <auto-generated/>
#nullable enable
namespace LuminaSharp
{
    /// <summary>Registers every engine [ManagedExport] (by name) into ManagedExportRegistry. Called once at
    /// bootstrap; native then resolves each managed entry by name. No C++ struct mirror, no layout/hash.</summary>
    internal static unsafe class ManagedExportTable
    {
        public static void RegisterEngineExports()
        {
");
        foreach (Model m in exports)
        {
            sb.Append("            global::LuminaSharp.ManagedExportRegistry.RegisterEngine(\"")
              .Append(m.ExportName)
              .Append("\", (global::System.IntPtr)(void*)(delegate* unmanaged[Stdcall]<")
              .Append(m.Signature).Append(">)&")
              .Append(m.ContainingType).Append('.').Append(m.Method).Append(");\n");
        }
        sb.Append("        }\n    }\n}\n");

        spc.AddSource("ManagedExports.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
