using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LuminaSharp.Generators;

/// <summary>
/// Source generator for native engine bindings. A method marked <c>[NativeCall] partial</c> gets its
/// implementation generated: the <c>delegate* unmanaged[Cdecl]</c> field resolved once via NativeBindings,
/// plus the marshalled body. Zero runtime overhead - the generated body is the same hand-written delegate*
/// call, minus the boilerplate. Used by both hand-written engine bindings (static, on <c>Native</c>) and the
/// Reflector's generated wrappers (instance methods that pass the object <c>Handle</c>).
///
/// Marshalling (mirrors the Reflector's C++ thunk ABI): string arg -&gt; (byte*, int) UTF-8; bool -&gt; byte
/// (the thunk uses unsigned char; reading the low byte is also correct for int-returning hand exports);
/// enum -&gt; int; LuminaSharp.Entity -&gt; uint (the entt id); Span&lt;T&gt;/ReadOnlySpan&lt;T&gt; arg -&gt;
/// (T* pinned, int Length); everything else (numerics, blittable value structs) passes by value. A `string`
/// RETURN uses the engine two-pass buffer ABI: the native export takes a trailing (byte* buffer, int capacity)
/// and returns the byte length (the generator calls it once with (null, 0) to size, then into an exact buffer).
/// Instance methods prepend the object Handle as the first native argument.
/// Defaults: module "LuminaNative", entry point "LuminaSharp_{MethodName}".
/// </summary>
[Generator]
public sealed class NativeCallGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "LuminaSharp.NativeCallAttribute";
    private const string DefaultModule = "LuminaNative";
    private const string EntityType = "global::LuminaSharp.Entity";

    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace LuminaSharp
{
    /// <summary>
    /// Marks a <c>partial</c> method whose body is generated as a native binding. Module defaults to
    /// ""LuminaNative""; entry point defaults to ""LuminaSharp_"" + the method name. Instance methods
    /// pass the object Handle as the first native argument.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
    internal sealed class NativeCallAttribute : global::System.Attribute
    {
        public NativeCallAttribute() { }
        public NativeCallAttribute(string entryPoint) { EntryPoint = entryPoint; }
        public string? Module { get; set; }
        public string? EntryPoint { get; set; }

        /// <summary>Skip the GC-mode switch on the call. Only valid for a short, non-blocking native leaf that
        /// never re-enters managed, blocks, or runs long; otherwise it can stall or deadlock the GC.</summary>
        public bool SuppressGCTransition { get; set; }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("NativeCallAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<Model?> models = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            predicate: static (node, _) => node is MethodDeclarationSyntax m
                && m.Modifiers.Any(t => t.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)),
            transform: static (ctx, ct) => BuildModel(ctx, ct));

        IncrementalValueProvider<ImmutableArray<Model?>> collected = models.Collect();

        context.RegisterSourceOutput(collected, static (spc, all) => Emit(spc, all));
    }

    private sealed record Model(string Namespace, string ClassName, string ClassModifiers, string TypeKeyword, string Member);

    private enum Kind { Pass, String, Bool, Enum, Entity }

    private static Model? BuildModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method)
        {
            return null;
        }

        INamedTypeSymbol type = method.ContainingType;

        // Read [NativeCall] module + entry point (ctor arg or named); apply the conventional defaults.
        string? module = null;
        string? entry = null;
        bool suppressGCTransition = false;
        AttributeData attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is string ctorEntry)
        {
            entry = ctorEntry;
        }
        foreach (KeyValuePair<string, TypedConstant> named in attr.NamedArguments)
        {
            if (named.Key == "Module" && named.Value.Value is string m)
            {
                module = m;
            }
            else if (named.Key == "EntryPoint" && named.Value.Value is string e)
            {
                entry = e;
            }
            else if (named.Key == "SuppressGCTransition" && named.Value.Value is bool s)
            {
                suppressGCTransition = s;
            }
        }
        module ??= DefaultModule;
        entry ??= "LuminaSharp_" + method.Name;

        SymbolDisplayFormat fq = SymbolDisplayFormat.FullyQualifiedFormat;

        var nativeTypes = new List<string>();
        var callArgs = new List<string>();
        var stringParams = new List<(int Index, string Name)>();
        var spanParams = new List<(int Index, string Name, string Elem)>();
        var sigParams = new List<string>();

        // Instance methods route through the object's native Handle as the first thunk argument (the
        // static delegate* field is still shared across instances - only the call passes `this.Handle`).
        // The handle's native type is taken from a `Handle` member on the containing type, so a facade
        // struct whose handle is a `ulong` passes a ulong (NativeObject/NativeStruct expose an IntPtr).
        if (!method.IsStatic)
        {
            string? handleTypeFq = FindHandleType(type, fq);
            if (handleTypeFq == null)
            {
                return null;
            }
            nativeTypes.Add(handleTypeFq);
            callArgs.Add("Handle");
        }

        for (int i = 0; i < method.Parameters.Length; i++)
        {
            IParameterSymbol p = method.Parameters[i];
            string name = p.Name;
            string typeFq = p.Type.ToDisplayString(fq);
            sigParams.Add($"{typeFq} {name}");

            // Span<T>/ReadOnlySpan<T> -> (T* pinned, int Length). Pinned in the generated body with `fixed`.
            if (TryGetSpanElement(p.Type, fq, out string spanElem))
            {
                nativeTypes.Add($"{spanElem}*");
                nativeTypes.Add("int");
                callArgs.Add($"__sp{i}");
                callArgs.Add($"{name}.Length");
                spanParams.Add((i, name, spanElem));
                continue;
            }

            // Wrapper arg (NativeObject/NativeStruct subclass) -> the engine handle (IntPtr), zero for null.
            if (IsNativeRef(p.Type))
            {
                nativeTypes.Add("global::System.IntPtr");
                callArgs.Add($"({name} is null ? global::System.IntPtr.Zero : {name}.Handle)");
                continue;
            }

            switch (Classify(p.Type, typeFq))
            {
                case Kind.String:
                    nativeTypes.Add("byte*");
                    nativeTypes.Add("int");
                    callArgs.Add($"__enc{i}.Pointer");
                    callArgs.Add($"__enc{i}.Length");
                    stringParams.Add((i, name));
                    break;
                case Kind.Bool:
                    nativeTypes.Add("byte");
                    callArgs.Add($"({name} ? (byte)1 : (byte)0)");
                    break;
                case Kind.Enum:
                    nativeTypes.Add("int");
                    callArgs.Add($"(int){name}");
                    break;
                case Kind.Entity:
                    nativeTypes.Add("uint");
                    callArgs.Add($"{name}.Id");
                    break;
                default:
                    nativeTypes.Add(typeFq);
                    callArgs.Add(name);
                    break;
            }
        }

        // Return shape. A `string` return uses the engine two-pass buffer ABI: the native export takes a
        // trailing (byte* buffer, int capacity) and returns the byte length; the body sizes with (null, 0)
        // then copies into an exact buffer. Everything else appends one native return type + a wrap().
        string retCs;
        System.Func<string, string> wrap = call => call;
        bool stringReturn = false;
        bool nativeRefReturn = false;
        string nativeRefRetType = string.Empty;
        if (method.ReturnsVoid)
        {
            retCs = "void";
            nativeTypes.Add("void");
        }
        else if (IsNativeRef(method.ReturnType))
        {
            nativeRefRetType = method.ReturnType.ToDisplayString(fq);
            retCs = nativeRefRetType + "?";
            nativeRefReturn = true;
            nativeTypes.Add("global::System.IntPtr");
        }
        else
        {
            string retFq = method.ReturnType.ToDisplayString(fq);
            retCs = retFq;
            switch (Classify(method.ReturnType, retFq))
            {
                case Kind.String:
                    stringReturn = true;
                    nativeTypes.Add("byte*");   // trailing caller buffer
                    nativeTypes.Add("int");     // trailing buffer capacity
                    nativeTypes.Add("int");     // returned byte length
                    break;
                case Kind.Bool:
                    nativeTypes.Add("byte");
                    wrap = call => $"{call} != 0";
                    break;
                case Kind.Enum:
                    nativeTypes.Add("int");
                    wrap = call => $"({retFq}){call}";
                    break;
                case Kind.Entity:
                    nativeTypes.Add("uint");
                    wrap = call => $"new {EntityType}({call})";
                    break;
                default:
                    nativeTypes.Add(retFq);
                    break;
            }
        }

        string callConv = suppressGCTransition ? "Cdecl, SuppressGCTransition" : "Cdecl";
        string delegateType = $"delegate* unmanaged[{callConv}]<{string.Join(", ", nativeTypes)}>";
        string field = $"__nc_{method.Name}";
        string coreArgs = string.Join(", ", callArgs);
        string staticMod = method.IsStatic ? " static" : string.Empty;
        string acc = Accessibility(method.DeclaredAccessibility);
        string sig = $"{acc}{staticMod} partial {retCs} {method.Name}({string.Join(", ", sigParams)})";

        var sb = new StringBuilder();
        sb.Append("        private static readonly ").Append(delegateType).Append(' ').Append(field).Append(" =\n");
        sb.Append("            (").Append(delegateType).Append(")global::LuminaSharp.NativeBindings.Resolve(\"")
          .Append(module).Append("\", \"").Append(entry).Append("\");\n");
        sb.Append("        ").Append(sig).Append('\n');

        static string Pad(int n) => new string(' ', n);

        // The native call itself (params already marshalled into coreArgs; span pointers pinned in scope).
        string CoreBody(int indent)
        {
            string pad = Pad(indent);
            if (stringReturn)
            {
                string prefix = callArgs.Count > 0 ? coreArgs + ", " : string.Empty;
                return pad + "int __len = " + field + "(" + prefix + "null, 0);\n"
                     + pad + "if (__len <= 0) { return string.Empty; }\n"
                     + pad + "byte[] __buf = new byte[__len];\n"
                     + pad + "fixed (byte* __bp = __buf)\n" + pad + "{\n"
                     + pad + "    int __w = " + field + "(" + prefix + "__bp, __len);\n"
                     + pad + "    return global::LuminaSharp.Interop.GetString(__bp, __w < __len ? __w : __len);\n"
                     + pad + "}\n";
            }
            if (nativeRefReturn)
            {
                return pad + "global::System.IntPtr __p = " + field + "(" + coreArgs + ");\n"
                     + pad + "return __p == global::System.IntPtr.Zero ? null : new " + nativeRefRetType + "(__p);\n";
            }
            if (method.ReturnsVoid)
            {
                return pad + field + "(" + coreArgs + ");\n";
            }
            return pad + "return " + wrap($"{field}({coreArgs})") + ";\n";
        }

        bool hasStrings = stringParams.Count > 0;
        bool hasSpans = spanParams.Count > 0;

        // Trivial shape (no marshalling fixups, plain return): expression body / one-liner.
        if (!hasStrings && !hasSpans && !stringReturn && !nativeRefReturn)
        {
            if (method.ReturnsVoid)
            {
                sb.Append("        {\n").Append(CoreBody(12)).Append("        }\n");
            }
            else
            {
                sb.Append("            => ").Append(wrap($"{field}({coreArgs})")).Append(";\n");
            }
        }
        else
        {
            sb.Append("        {\n");
            int indent = 12;

            // String args: encode UTF-8 into stack scratch (allocation-free when it fits), free in finally.
            foreach ((int idx, string name) in stringParams)
            {
                sb.Append(Pad(indent)).Append("global::System.Span<byte> __sb").Append(idx).Append(" = stackalloc byte[256];\n");
                sb.Append(Pad(indent)).Append("global::LuminaSharp.Interop.FInteropString __enc").Append(idx)
                  .Append(" = new(").Append(name).Append(", __sb").Append(idx).Append(");\n");
            }

            if (hasStrings)
            {
                sb.Append(Pad(indent)).Append("try\n").Append(Pad(indent)).Append("{\n");
                indent += 4;
            }

            // Span args: stacked `fixed` pins wrapping the call.
            foreach ((int idx, string name, string elem) in spanParams)
            {
                sb.Append(Pad(indent)).Append("fixed (").Append(elem).Append("* __sp").Append(idx)
                  .Append(" = ").Append(name).Append(")\n");
            }
            if (hasSpans)
            {
                sb.Append(Pad(indent)).Append("{\n");
                sb.Append(CoreBody(indent + 4));
                sb.Append(Pad(indent)).Append("}\n");
            }
            else
            {
                sb.Append(CoreBody(indent));
            }

            if (hasStrings)
            {
                indent -= 4;
                sb.Append(Pad(indent)).Append("}\n").Append(Pad(indent)).Append("finally\n").Append(Pad(indent)).Append("{\n");
                foreach ((int idx, string _) in stringParams)
                {
                    sb.Append(Pad(indent + 4)).Append("__enc").Append(idx).Append(".Free();\n");
                }
                sb.Append(Pad(indent)).Append("}\n");
            }

            sb.Append("        }\n");
        }

        string ns = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

        // The partial we emit must agree with the primary declaration: `struct` for a struct (carrying
        // `readonly` when the type is a readonly struct), `class` otherwise. Static applies to classes.
        bool isStruct = type.TypeKind == TypeKind.Struct;
        string typeKeyword = isStruct ? "struct" : "class";
        string readonlyMod = isStruct && type.IsReadOnly ? " readonly" : string.Empty;
        string staticTypeMod = !isStruct && type.IsStatic ? " static" : string.Empty;
        string classMods = $"{Accessibility(type.DeclaredAccessibility)}{staticTypeMod}{readonlyMod} unsafe partial";

        return new Model(ns, type.Name, classMods, typeKeyword, sb.ToString());
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<Model?> all)
    {
        IEnumerable<Model> models = all.Where(m => m is not null).Select(m => m!);

        foreach (IGrouping<(string Namespace, string ClassName, string ClassModifiers, string TypeKeyword), Model> group in
                 models.GroupBy(m => (m.Namespace, m.ClassName, m.ClassModifiers, m.TypeKeyword)))
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n#nullable enable\n");

            bool hasNs = group.Key.Namespace.Length > 0;
            if (hasNs)
            {
                sb.Append("namespace ").Append(group.Key.Namespace).Append("\n{\n");
            }
            sb.Append("    ").Append(group.Key.ClassModifiers).Append(' ').Append(group.Key.TypeKeyword)
              .Append(' ').Append(group.Key.ClassName).Append("\n    {\n");
            foreach (Model model in group)
            {
                sb.Append(model.Member);
            }
            sb.Append("    }\n");
            if (hasNs)
            {
                sb.Append("}\n");
            }

            string hint = (hasNs ? group.Key.Namespace + "." : string.Empty) + group.Key.ClassName + ".NativeCall.g.cs";
            spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    // The native type of an instance method's leading handle argument is read from a `Handle` field or
    // property on the containing type (walking base types). Returns null when no such member exists, so a
    // non-static [NativeCall] method on a type without a Handle is skipped rather than emitting bad code.
    private static string? FindHandleType(INamedTypeSymbol type, SymbolDisplayFormat fq)
    {
        for (INamedTypeSymbol? current = type; current != null; current = current.BaseType)
        {
            foreach (ISymbol member in current.GetMembers("Handle"))
            {
                ITypeSymbol? handleType = member switch
                {
                    IFieldSymbol field => field.Type,
                    IPropertySymbol property => property.Type,
                    _ => null,
                };
                if (handleType != null)
                {
                    return handleType.ToDisplayString(fq);
                }
            }
        }
        return null;
    }

    // A C# wrapper over a native handle: a class deriving LuminaSharp.NativeObject / NativeStruct (the
    // Reflector's opaque wrappers + the facades). Such a type marshals as its `Handle` (an arg) or is
    // reconstructed from a returned handle. Blittable value-mirror structs are NOT native refs (no base).
    private static bool IsNativeRef(ITypeSymbol type)
    {
        for (INamedTypeSymbol? t = type as INamedTypeSymbol; t != null; t = t.BaseType)
        {
            if ((t.Name == "NativeObject" || t.Name == "NativeStruct")
                && t.ContainingNamespace?.ToDisplayString() == "LuminaSharp")
            {
                return true;
            }
        }
        return false;
    }

    // Span<T>/ReadOnlySpan<T> -> (T* pinned, int Length). T must be unmanaged (the generated `fixed` pin
    // enforces it at compile time). Returns the fully-qualified element type, or false for non-span types.
    private static bool TryGetSpanElement(ITypeSymbol type, SymbolDisplayFormat fq, out string elementFq)
    {
        elementFq = string.Empty;
        if (type is INamedTypeSymbol named && named.IsGenericType && named.TypeArguments.Length == 1)
        {
            string unbound = named.ConstructedFrom.ToDisplayString();
            if (unbound == "System.Span<T>" || unbound == "System.ReadOnlySpan<T>")
            {
                elementFq = named.TypeArguments[0].ToDisplayString(fq);
                return true;
            }
        }
        return false;
    }

    private static Kind Classify(ITypeSymbol type, string fqName)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            return Kind.String;
        }
        if (type.SpecialType == SpecialType.System_Boolean)
        {
            return Kind.Bool;
        }
        if (type.TypeKind == TypeKind.Enum)
        {
            return Kind.Enum;
        }
        if (fqName == EntityType)
        {
            return Kind.Entity;
        }
        return Kind.Pass;
    }

    private static string Accessibility(Accessibility a) => a switch
    {
        Microsoft.CodeAnalysis.Accessibility.Public => "public",
        Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
        Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
        Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
        Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
        Microsoft.CodeAnalysis.Accessibility.Private => "private",
        _ => string.Empty,
    };
}
