using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LuminaSharp.Generators;

/// <summary>
/// Source generator for native engine bindings. A method marked <c>[NativeCall] partial</c> gets its
/// implementation generated: the <c>delegate* unmanaged[Cdecl]</c> field resolved once via NativeBindings,
/// plus the marshalled body. Zero runtime overhead - the generated body is the same hand-written delegate*
/// call, minus the boilerplate. Used by both hand-written engine bindings (static, on <c>Native</c>) and the
/// Reflector's generated wrappers (instance methods that pass the object <c>Handle</c>).
///
/// Marshalling (mirrors the Reflector's C++ thunk ABI): string -&gt; (byte*, int) UTF-8; bool -&gt; byte
/// (the thunk uses unsigned char; reading the low byte is also correct for int-returning hand exports);
/// enum -&gt; int; LuminaSharp.Entity -&gt; uint (the entt id); everything else (numerics, blittable value
/// structs) passes by value. Instance methods prepend the object Handle as the first native argument.
/// Defaults: module "LuminaNative", entry point "LuminaSharp_{MethodName}".
/// </summary>
[Generator]
public sealed class NativeCallGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "LuminaSharp.NativeCallAttribute";
    private const string DefaultModule = "LuminaNative";
    private const string EntityType = "global::LuminaSharp.Entity";

    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace LuminaSharp
{
    /// <summary>
    /// Marks a <c>partial</c> method whose body is generated as a native binding. Module defaults to
    /// ""LuminaNative""; entry point defaults to ""LuminaSharp_"" + the method name. Instance methods
    /// pass the object Handle as the first native argument.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
    internal sealed class NativeCallAttribute : global::System.Attribute
    {
        public NativeCallAttribute() { }
        public NativeCallAttribute(string entryPoint) { EntryPoint = entryPoint; }
        public string? Module { get; set; }
        public string? EntryPoint { get; set; }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("NativeCallAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<Model?> models = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            predicate: static (node, _) => node is MethodDeclarationSyntax m
                && m.Modifiers.Any(t => t.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)),
            transform: static (ctx, ct) => BuildModel(ctx, ct));

        IncrementalValueProvider<ImmutableArray<Model?>> collected = models.Collect();

        context.RegisterSourceOutput(collected, static (spc, all) => Emit(spc, all));
    }

    private sealed record Model(string Namespace, string ClassName, string ClassModifiers, string TypeKeyword, string Member);

    private enum Kind { Pass, String, Bool, Enum, Entity }

    private static Model? BuildModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method)
        {
            return null;
        }

        INamedTypeSymbol type = method.ContainingType;

        // Read [NativeCall] module + entry point (ctor arg or named); apply the conventional defaults.
        string? module = null;
        string? entry = null;
        AttributeData attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is string ctorEntry)
        {
            entry = ctorEntry;
        }
        foreach (KeyValuePair<string, TypedConstant> named in attr.NamedArguments)
        {
            if (named.Key == "Module" && named.Value.Value is string m)
            {
                module = m;
            }
            else if (named.Key == "EntryPoint" && named.Value.Value is string e)
            {
                entry = e;
            }
        }
        module ??= DefaultModule;
        entry ??= "LuminaSharp_" + method.Name;

        SymbolDisplayFormat fq = SymbolDisplayFormat.FullyQualifiedFormat;

        var nativeTypes = new List<string>();
        var callArgs = new List<string>();
        var stringParams = new List<(int Index, string Name)>();
        var sigParams = new List<string>();

        // Instance methods route through the object's native Handle as the first thunk argument (the
        // static delegate* field is still shared across instances - only the call passes `this.Handle`).
        // The handle's native type is taken from a `Handle` member on the containing type, so a facade
        // struct whose handle is a `ulong` passes a ulong (NativeObject/NativeStruct expose an IntPtr).
        if (!method.IsStatic)
        {
            string? handleTypeFq = FindHandleType(type, fq);
            if (handleTypeFq == null)
            {
                return null;
            }
            nativeTypes.Add(handleTypeFq);
            callArgs.Add("Handle");
        }

        for (int i = 0; i < method.Parameters.Length; i++)
        {
            IParameterSymbol p = method.Parameters[i];
            string name = p.Name;
            string typeFq = p.Type.ToDisplayString(fq);
            sigParams.Add($"{typeFq} {name}");

            switch (Classify(p.Type, typeFq))
            {
                case Kind.String:
                    nativeTypes.Add("byte*");
                    nativeTypes.Add("int");
                    callArgs.Add($"__enc{i}.Pointer");
                    callArgs.Add($"__enc{i}.Length");
                    stringParams.Add((i, name));
                    break;
                case Kind.Bool:
                    nativeTypes.Add("byte");
                    callArgs.Add($"({name} ? (byte)1 : (byte)0)");
                    break;
                case Kind.Enum:
                    nativeTypes.Add("int");
                    callArgs.Add($"(int){name}");
                    break;
                case Kind.Entity:
                    nativeTypes.Add("uint");
                    callArgs.Add($"{name}.Id");
                    break;
                default:
                    nativeTypes.Add(typeFq);
                    callArgs.Add(name);
                    break;
            }
        }

        // Return shape: native delegate* return type + a function that wraps the raw call expression.
        string retCs;
        System.Func<string, string> wrap;
        if (method.ReturnsVoid)
        {
            retCs = "void";
            nativeTypes.Add("void");
            wrap = call => call; // unused for void
        }
        else
        {
            string retFq = method.ReturnType.ToDisplayString(fq);
            retCs = retFq;
            switch (Classify(method.ReturnType, retFq))
            {
                case Kind.Bool:
                    nativeTypes.Add("byte");
                    wrap = call => $"{call} != 0";
                    break;
                case Kind.Enum:
                    nativeTypes.Add("int");
                    wrap = call => $"({retFq}){call}";
                    break;
                case Kind.Entity:
                    nativeTypes.Add("uint");
                    wrap = call => $"new {EntityType}({call})";
                    break;
                default:
                    nativeTypes.Add(retFq);
                    wrap = call => call;
                    break;
            }
        }

        string delegateType = $"delegate* unmanaged[Cdecl]<{string.Join(", ", nativeTypes)}>";
        string field = $"__nc_{method.Name}";
        string callExpr = $"{field}({string.Join(", ", callArgs)})";
        string staticMod = method.IsStatic ? " static" : string.Empty;
        string acc = Accessibility(method.DeclaredAccessibility);
        string sig = $"{acc}{staticMod} partial {retCs} {method.Name}({string.Join(", ", sigParams)})";

        var sb = new StringBuilder();
        sb.Append("        private static readonly ").Append(delegateType).Append(' ').Append(field).Append(" =\n");
        sb.Append("            (").Append(delegateType).Append(")global::LuminaSharp.NativeBindings.Resolve(\"")
          .Append(module).Append("\", \"").Append(entry).Append("\");\n");
        sb.Append("        ").Append(sig).Append('\n');

        // Body. With string args we pin/encode each (allocation-free when it fits the stack scratch) and
        // free in a finally; otherwise an expression body suffices.
        if (stringParams.Count == 0)
        {
            if (method.ReturnsVoid)
            {
                sb.Append("        {\n            ").Append(callExpr).Append(";\n        }\n");
            }
            else
            {
                sb.Append("            => ").Append(wrap(callExpr)).Append(";\n");
            }
        }
        else
        {
            sb.Append("        {\n");
            foreach ((int idx, string name) in stringParams)
            {
                sb.Append("            global::System.Span<byte> __sb").Append(idx).Append(" = stackalloc byte[256];\n");
                sb.Append("            global::LuminaSharp.Interop.FInteropString __enc").Append(idx)
                  .Append(" = new(").Append(name).Append(", __sb").Append(idx).Append(");\n");
            }
            sb.Append("            try\n            {\n");
            if (method.ReturnsVoid)
            {
                sb.Append("                ").Append(callExpr).Append(";\n");
            }
            else
            {
                sb.Append("                return ").Append(wrap(callExpr)).Append(";\n");
            }
            sb.Append("            }\n            finally\n            {\n");
            foreach ((int idx, string _) in stringParams)
            {
                sb.Append("                __enc").Append(idx).Append(".Free();\n");
            }
            sb.Append("            }\n        }\n");
        }

        string ns = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

        // The partial we emit must agree with the primary declaration: `struct` for a struct (carrying
        // `readonly` when the type is a readonly struct), `class` otherwise. Static applies to classes.
        bool isStruct = type.TypeKind == TypeKind.Struct;
        string typeKeyword = isStruct ? "struct" : "class";
        string readonlyMod = isStruct && type.IsReadOnly ? " readonly" : string.Empty;
        string staticTypeMod = !isStruct && type.IsStatic ? " static" : string.Empty;
        string classMods = $"{Accessibility(type.DeclaredAccessibility)}{staticTypeMod}{readonlyMod} unsafe partial";

        return new Model(ns, type.Name, classMods, typeKeyword, sb.ToString());
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<Model?> all)
    {
        IEnumerable<Model> models = all.Where(m => m is not null).Select(m => m!);

        foreach (IGrouping<(string Namespace, string ClassName, string ClassModifiers, string TypeKeyword), Model> group in
                 models.GroupBy(m => (m.Namespace, m.ClassName, m.ClassModifiers, m.TypeKeyword)))
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n#nullable enable\n");

            bool hasNs = group.Key.Namespace.Length > 0;
            if (hasNs)
            {
                sb.Append("namespace ").Append(group.Key.Namespace).Append("\n{\n");
            }
            sb.Append("    ").Append(group.Key.ClassModifiers).Append(' ').Append(group.Key.TypeKeyword)
              .Append(' ').Append(group.Key.ClassName).Append("\n    {\n");
            foreach (Model model in group)
            {
                sb.Append(model.Member);
            }
            sb.Append("    }\n");
            if (hasNs)
            {
                sb.Append("}\n");
            }

            string hint = (hasNs ? group.Key.Namespace + "." : string.Empty) + group.Key.ClassName + ".NativeCall.g.cs";
            spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    // The native type of an instance method's leading handle argument is read from a `Handle` field or
    // property on the containing type (walking base types). Returns null when no such member exists, so a
    // non-static [NativeCall] method on a type without a Handle is skipped rather than emitting bad code.
    private static string? FindHandleType(INamedTypeSymbol type, SymbolDisplayFormat fq)
    {
        for (INamedTypeSymbol? current = type; current != null; current = current.BaseType)
        {
            foreach (ISymbol member in current.GetMembers("Handle"))
            {
                ITypeSymbol? handleType = member switch
                {
                    IFieldSymbol field => field.Type,
                    IPropertySymbol property => property.Type,
                    _ => null,
                };
                if (handleType != null)
                {
                    return handleType.ToDisplayString(fq);
                }
            }
        }
        return null;
    }

    private static Kind Classify(ITypeSymbol type, string fqName)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            return Kind.String;
        }
        if (type.SpecialType == SpecialType.System_Boolean)
        {
            return Kind.Bool;
        }
        if (type.TypeKind == TypeKind.Enum)
        {
            return Kind.Enum;
        }
        if (fqName == EntityType)
        {
            return Kind.Entity;
        }
        return Kind.Pass;
    }

    private static string Accessibility(Accessibility a) => a switch
    {
        Microsoft.CodeAnalysis.Accessibility.Public => "public",
        Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
        Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
        Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
        Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
        Microsoft.CodeAnalysis.Accessibility.Private => "private",
        _ => string.Empty,
    };
}
