#include "CodeGenerator.h"

#include <filesystem>
#include <fstream>

#include <EASTL/hash_map.h>
#include <EASTL/hash_set.h>
#include <EASTL/string.h>
#include <EASTL/vector.h>

#include "CodeWriter.h"
#include "ReflectionNames.h"
#include "Reflector/ProjectSolution.h"
#include "Reflector/ReflectionCore/ReflectedHeader.h"
#include "Reflector/ReflectionCore/ReflectedProject.h"
#include "Reflector/Types/Properties/ReflectedProperty.h"
#include "Reflector/Types/ReflectedType.h"
#include "StringHash.h"

namespace Lumina::Reflection
{
    namespace
    {
        constexpr size_t kStreamInitialCapacity = 10 * 1024;

        // Express the header relative to a project -I dir (longest match) or the project root.
        // A relative form lets the generated artifact survive being moved or rebuilt elsewhere.
        eastl::string ComputeSourceHeaderInclude(const FReflectedHeader& Header)
        {
            const eastl::string& Path = Header.HeaderPath;
            const FReflectedProject& Proj = *Header.Project;

            auto TryStrip = [&](const eastl::string& Prefix) -> eastl::string
            {
                if (Prefix.empty() || Prefix.size() >= Path.size())
                {
                    return {};
                }
                if (Path.compare(0, Prefix.size(), Prefix) != 0)
                {
                    return {};
                }
                size_t Pos = Prefix.size();
                while (Pos < Path.size() && (Path[Pos] == '/' || Path[Pos] == '\\'))
                {
                    ++Pos;
                }
                if (Pos >= Path.size())
                {
                    return {};
                }
                return Path.substr(Pos);
            };

            const eastl::string* BestPrefix = nullptr;
            eastl::string BestRel;
            for (const eastl::string& Dir : Proj.IncludeDirs)
            {
                eastl::string Rel = TryStrip(Dir);
                if (!Rel.empty() && (BestPrefix == nullptr || Dir.size() > BestPrefix->size()))
                {
                    BestPrefix = &Dir;
                    BestRel = eastl::move(Rel);
                }
            }
            if (BestPrefix != nullptr)
            {
                return BestRel;
            }

            if (eastl::string Rel = TryStrip(Proj.Path); !Rel.empty())
            {
                return Rel;
            }

            // No prefix matched -- keep absolute. Better to bake in the path
            // than silently emit something the compiler can't resolve.
            return Path;
        }

        void EmitFileBanner(FCodeWriter& Writer)
        {
            Writer.Line("//*************************************************************************");
            Writer.Line("// Generated by Lumina Reflection Tool. ");
            Writer.Line("// This is an auto-generated file - DO NOT EDIT.");
            Writer.Line("//*************************************************************************");
            Writer.Line();
        }

        // Paths produced by generation, relative to the workspace root.
        eastl::string MakeGeneratedHeaderPath(const eastl::string& WorkspacePath, const FReflectedHeader& Header)
        {
            return WorkspacePath + R"(\Intermediates\Reflection\)" + Header.Project->Name + R"(\)" + Header.FileName + ".generated.h";
        }

        eastl::string MakeGeneratedSourcePath(const eastl::string& WorkspacePath, const FReflectedHeader& Header)
        {
            return WorkspacePath + R"(\Intermediates\Reflection\)" + Header.Project->Name + R"(\)" + Header.FileName + ".generated.cpp";
        }

        eastl::string MakeUnityPath(const eastl::string& WorkspacePath, const FReflectedProject& Project)
        {
            return WorkspacePath + R"(\Intermediates\Reflection\)" + Project.Name + R"(\ReflectionUnity.gen.cpp)";
        }

        eastl::string MakeProjectIntermediateDir(const eastl::string& WorkspacePath, const FReflectedProject& Project)
        {
            return WorkspacePath + R"(\Intermediates\Reflection\)" + Project.Name;
        }

        constexpr const char* kUnityStubContents =
            "// Reflection unity stub.\n"
            "// This project has no reflected types yet; this file exists\n"
            "// only so the vcxproj's source list resolves. The Reflector\n"
            "// will overwrite it the moment a reflected type appears.\n"
            "#if __has_include(\"pch.h\")\n"
            "    #include \"pch.h\"\n"
            "#endif\n";

        void WriteTextFile(const eastl::string& PathUtf8, const eastl::string& Contents)
        {
            std::filesystem::path OutputPath(PathUtf8.c_str());
            std::filesystem::create_directories(OutputPath.parent_path());

            std::ofstream Stream(OutputPath);
            if (Stream.is_open())
            {
                Stream.write(Contents.c_str(), static_cast<std::streamsize>(Contents.size()));
            }
        }
    }

    FCodeGenerator::FCodeGenerator(FReflectedWorkspace* InWorkspace, const FReflectionDatabase& Database)
        : Workspace(InWorkspace)
        , ReflectionDatabase(&Database)
    {
    }

    void FCodeGenerator::GenerateCode()
    {
        // Per-project accumulator: unity cpp pools every dirty header's
        // .generated.cpp include.
        eastl::hash_map<FReflectedProject*, eastl::string>                  UnityPerProject;
        eastl::hash_set<FReflectedProject*>                                 DirtyProjects;
        eastl::hash_map<FReflectedProject*, eastl::hash_set<eastl::string>> ExpectedArtifacts;

        for (const auto& [Header, _] : ReflectionDatabase->ReflectedTypes)
        {
            eastl::string& Unity = UnityPerProject[Header->Project];
            if (Unity.empty())
            {
                Unity += "#include \"pch.h\"\n";
            }
            Unity += "#include \"" + Header->FileName + ".generated.cpp\"\n";

            auto& Expected = ExpectedArtifacts[Header->Project];
            Expected.insert(Header->FileName + ".generated.cpp");
            Expected.insert(Header->FileName + ".generated.h");

            if (Header->bDirty)
            {
                DirtyProjects.insert(Header->Project);
                GenerateHeaderFile(Header);
                GenerateSourceFile(Header);
            }
        }

        // Orphan sweep: a deleted header leaves stale .generated.{h,cpp} the loop above never sees.
        // Remove any generated artifact whose backing header is gone and mark the project dirty.
        for (auto& Project : Workspace->ReflectedProjects)
        {
            const std::filesystem::path Dir(
                MakeProjectIntermediateDir(Workspace->GetPath(), *Project).c_str());

            std::error_code Ec;
            if (!std::filesystem::exists(Dir, Ec))
            {
                continue;
            }

            const auto* Expected = [&]() -> const eastl::hash_set<eastl::string>*
            {
                auto It = ExpectedArtifacts.find(Project.get());
                return It != ExpectedArtifacts.end() ? &It->second : nullptr;
            }();

            for (const auto& Entry : std::filesystem::directory_iterator(Dir, Ec))
            {
                if (Ec || !Entry.is_regular_file(Ec))
                {
                    continue;
                }

                const std::string FilenameStd = Entry.path().filename().string();
                const eastl::string Filename(FilenameStd.c_str());

                const bool bIsGenerated =
                    Filename.find(".generated.cpp") != eastl::string::npos ||
                    Filename.find(".generated.h") != eastl::string::npos;
                if (!bIsGenerated)
                {
                    continue;
                }

                if (Expected && Expected->find(Filename) != Expected->end())
                {
                    continue;
                }

                std::filesystem::remove(Entry.path(), Ec);
                DirtyProjects.insert(Project.get());
            }
        }

        for (auto* DirtyProject : DirtyProjects)
        {
            // A project that lost its last reflected type has no UnityPerProject entry;
            // fall back to the stub so the vcxproj still compiles cleanly.
            auto It = UnityPerProject.find(DirtyProject);
            const bool bHasContent = It != UnityPerProject.end() && !It->second.empty();
            WriteUnityBuildFile(DirtyProject, bHasContent ? It->second : eastl::string(kUnityStubContents));
        }

        // Stub guard: ReflectionUnity.gen.cpp must exist even for projects with zero reflected types.
        // Only write when missing (keeps incremental builds fast); the __has_include stub works PCH or not.
        for (auto& Project : Workspace->ReflectedProjects)
        {
            const eastl::string Path = MakeUnityPath(Workspace->GetPath(), *Project);
            if (std::filesystem::exists(std::filesystem::path(Path.c_str())))
            {
                continue;
            }

            auto It = UnityPerProject.find(Project.get());
            const bool bHasContent = It != UnityPerProject.end() && !It->second.empty();
            WriteTextFile(Path, bHasContent ? It->second : eastl::string(kUnityStubContents));
        }
    }

    void FCodeGenerator::GenerateHeaderFile(FReflectedHeader* Header)
    {
        FCodeWriter Writer(kStreamInitialCapacity);
        WriteHeaderContent(Writer, Header);
        WriteTextFile(MakeGeneratedHeaderPath(Workspace->GetPath(), *Header), Writer.String());
    }

    void FCodeGenerator::GenerateSourceFile(FReflectedHeader* Header)
    {
        FCodeWriter Writer(kStreamInitialCapacity);
        WriteSourceContent(Writer, Header);
        WriteTextFile(MakeGeneratedSourcePath(Workspace->GetPath(), *Header), Writer.String());
    }

    void FCodeGenerator::WriteHeaderContent(FCodeWriter& Writer, FReflectedHeader* Header)
    {
        const auto& Types = ReflectionDatabase->ReflectedTypes.at(Header);
        const eastl::string FileID = Names::MakeFileIDForHeaderPath(Header->HeaderPath);

        Writer.Line("#pragma once");
        Writer.Line();
        EmitFileBanner(Writer);

        Writer.Line("#include \"Core/Reflection/ReflectedTypeAccessors.h\"");
        Writer.BlankLines(2);

        // Guard against double-inclusion without a #pragma once in the upstream header.
        Writer.Linef("#ifdef %s_generated_h", FileID.c_str());
        Writer.Line("#error Already included, missing #pragma once");
        Writer.Line("#endif");
        Writer.Linef("#define %s_generated_h", FileID.c_str());
        Writer.BlankLines(3);

        // Forward declarations + Construct_* decls + DECLARE_CLASS macros.
        for (const auto& Type : Types)
        {
            Type->DefineInitialHeader(Writer, FileID);
        }

        Writer.BlankLines(3);
        Writer.Line("//--------------------------------------------------------------------------------------");
        Writer.BlankLines(3);

        // GENERATED_BODY expansion macros.
        for (const auto& Type : Types)
        {
            Type->DefineSecondaryHeader(Writer, FileID);
        }

        Writer.BlankLines(3);
        Writer.Line("#undef CURRENT_FILE_ID ");
        Writer.Linef("\t #define CURRENT_FILE_ID %s", FileID.c_str());
    }

    namespace
    {
        // Cross-module references for every reflected type in this TU, plus one per
        // struct/class property that points at a type in another module.
        void EmitCrossModuleReferences(FCodeWriter& Writer, const FReflectionDatabase& Db,
            FReflectedHeader* Header, const eastl::vector<eastl::unique_ptr<FReflectedType>>& Types)
        {
            const eastl::string OwningApi = Names::ProjectApiMacro(Header->Project->Name);

            Writer.Line("// Begin Cross-Module References");

            for (const auto& Type : Types)
            {
                const eastl::string Kind = Type->GetTypeName();
                const eastl::string ConstructFn = Names::ConstructFunction(Kind, Type->Namespace, Type->DisplayName);
                Names::EmitGuardedCrossModuleDecl(Writer, OwningApi, Kind, ConstructFn);

                if (auto* Struct = dynamic_cast<FReflectedStruct*>(Type.get()))
                {
                    for (auto& Property : Struct->Props)
                    {
                        if (const auto* PropType = Db.GetReflectedType<FReflectedType>(FStringHash(Property->TypeName)))
                        {
                            const eastl::string PropApi = Names::ProjectApiMacro(PropType->Header->Project->Name);
                            Property->DeclareCrossModuleReference(PropApi, Writer);
                        }
                    }
                }
            }

            Writer.Line("// End Cross-Module References");
            Writer.Line();
        }

        // The per-file Register_Static_Initializer struct + trampoline.
        void EmitStaticRegistration(FCodeWriter& Writer, const eastl::string& FileID,
            const eastl::vector<eastl::unique_ptr<FReflectedType>>& Types)
        {
            bool bHasEnum = false;
            bool bHasClass = false;
            bool bHasStruct = false;

            for (const auto& Type : Types)
            {
                switch (Type->Type)
                {
                    case FReflectedType::EType::Enum:      bHasEnum   = true; break;
                    case FReflectedType::EType::Class:     bHasClass  = true; break;
                    case FReflectedType::EType::Structure: bHasStruct = true; break;
                }
            }

            Writer.Line("// ** Begin Static Registration **");
            Writer.Line();

            Writer.Linef("struct Registration_%s", FileID.c_str());
            Writer.BeginBlock();

            auto EmitInfoArray = [&](const char* FieldName, const char* ParamType, FReflectedType::EType Kind)
            {
                Writer.Linef("static constexpr Lumina::%s %s[] = {", ParamType, FieldName);
                for (const auto& Type : Types)
                {
                    if (Type->Type == Kind)
                    {
                        Type->DeclareStaticRegistration(Writer);
                    }
                }
                Writer.Line("};");
            };

            if (bHasEnum)
            {
                EmitInfoArray("EnumInfo", "FEnumRegisterCompiledInInfo", FReflectedType::EType::Enum);
            }
            if (bHasClass)
            {
                EmitInfoArray("ClassInfo", "FClassRegisterCompiledInInfo", FReflectedType::EType::Class);
            }
            if (bHasStruct)
            {
                EmitInfoArray("StructInfo", "FStructRegisterCompiledInInfo", FReflectedType::EType::Structure);
            }

            Writer.PopIndent();
            Writer.Line("};");

            // Trampoline that feeds the Registration_* struct into the compiled-in
            // registrar at translation-unit init time.
            Writer.Linef("static Lumina::FRegisterCompiledInInfo %s_Register_Static_Initializer(",
                FileID.c_str());

            auto EmitInfoPointer = [&](const char* ArrayName, bool bHasIt, bool bLast)
            {
                const char* Terminator = bLast ? "" : ",";
                if (bHasIt)
                {
                    Writer.Linef("\tRegistration_%s::%s,", FileID.c_str(), ArrayName);
                    Writer.Linef("\tstd::size(Registration_%s::%s)%s", FileID.c_str(), ArrayName, Terminator);
                }
                else
                {
                    Writer.Line("\tnullptr,");
                    Writer.Linef("\t0%s", Terminator);
                }
            };

            EmitInfoPointer("EnumInfo", bHasEnum, false);
            EmitInfoPointer("ClassInfo", bHasClass, false);
            EmitInfoPointer("StructInfo", bHasStruct, true);

            Writer.Line(");");
            Writer.Line();
            Writer.Line("// ** End Static Registration **");
            Writer.Line();
        }
    }

    void FCodeGenerator::WriteSourceContent(FCodeWriter& Writer, FReflectedHeader* Header)
    {
        Writer.Clear();

        const auto& Types = ReflectionDatabase->ReflectedTypes.at(Header);
        const eastl::string FileID = Names::MakeFileIDForHeaderPath(Header->HeaderPath);

        EmitFileBanner(Writer);

        Writer.Line("#include \"pch.h\"");
        Writer.Linef("#include \"%s\"", ComputeSourceHeaderInclude(*Header).c_str());
        Writer.Line("#include \"World/Entity/Components/Component.h\"");
        Writer.Line("#include \"World/Entity/Events/ECSEvent.h\"");
        Writer.Line("#include \"lua.h\"");
        Writer.Line("#include \"lualib.h\"");
        Writer.Line("#include \"Core/Profiler/Profile.h\"");
        Writer.Line("#include \"Core/Math/Hash/Hash.h\"");
        Writer.Line("#include \"Scripting/Lua/Invoker.h\"");
        Writer.Line("#include \"Scripting/Lua/Class.h\"");
        Writer.Line("#include \"Core/Object/Class.h\"");
        Writer.Line("using namespace entt::literals;");
        Writer.Line("using LuaMethodFn = int(*)(lua_State*);");
        Writer.BlankLines(2);

        EmitCrossModuleReferences(Writer, *ReflectionDatabase, Header, Types);

        Writer.Line("//*************************************************************************");
        Writer.Line("// Type Implementations. ");
        Writer.Line("//*************************************************************************");
        Writer.Line();
        for (const auto& Type : Types)
        {
            Type->DeclareImplementation(Writer);
        }

        Writer.BlankLines(2);
        EmitStaticRegistration(Writer, FileID, Types);
    }

    void FCodeGenerator::WriteUnityBuildFile(FReflectedProject* Project, const eastl::string& Contents)
    {
        WriteTextFile(MakeUnityPath(Workspace->GetPath(), *Project), Contents);
    }
}
