using System;
using System.Runtime.InteropServices;
using LuminaSharp;

namespace Lumina;

/// <summary>
/// Hand-written ergonomic half of <c>SDynamicMeshComponent</c> (the rest - <c>AddSection</c>, <c>Commit</c>,
/// <c>ClearMesh</c>, <c>IsBuilt</c>, <c>GetVertexCount</c>, <c>GetTriangleCount</c>, plus the inherited
/// material/shadow/culling members - is generated by the Reflector). Build a mesh from raw data at runtime
/// and render it through the normal pipeline; rebuild as often as you like (e.g. per voxel chunk).
///
/// <para>Typical use from an <see cref="EntityScript"/>:</para>
/// <code>
/// var mesh = Registry.GetOrAdd&lt;SDynamicMeshComponent&gt;(Entity)!;
/// mesh.ClearMesh();
/// mesh.SetPositions(positions);   // ReadOnlySpan&lt;FVector3&gt; / FVector3[]
/// mesh.SetIndices(indices);       // int[] or uint[]
/// mesh.SetUVs(uvs);               // optional
/// mesh.SetColors(colors);         // optional (FVector4 or packed uint)
/// mesh.Commit();                  // generates normals if absent, builds + uploads
/// </code>
///
/// Positions and indices are required; normals are derived (smooth) when not supplied, UVs default to zero,
/// colors to white. Set the streams, optionally carve <see cref="AddSection"/> ranges for multiple materials,
/// then <c>Commit</c>. Call on the game thread (e.g. OnReady / OnUpdate).
/// </summary>
public unsafe partial class SDynamicMeshComponent
{
    /// <summary>Vertex positions (one per vertex). Required.</summary>
    public void SetPositions(ReadOnlySpan<FVector3> Positions)
        => SetPositionsRaw(MemoryMarshal.Cast<FVector3, float>(Positions));

    /// <summary>Vertex normals (one per vertex). Optional - smooth normals are derived from the geometry when
    /// omitted or when the count doesn't match the vertices.</summary>
    public void SetNormals(ReadOnlySpan<FVector3> Normals)
        => SetNormalsRaw(MemoryMarshal.Cast<FVector3, float>(Normals));

    /// <summary>Vertex texture coordinates (one per vertex). Optional (defaults to zero).</summary>
    public void SetUVs(ReadOnlySpan<FVector2> UVs)
        => SetUVsRaw(MemoryMarshal.Cast<FVector2, float>(UVs));

    /// <summary>Per-vertex colors as linear RGBA floats. Optional (defaults to white).</summary>
    public void SetColors(ReadOnlySpan<FVector4> Colors)
        => SetColorsFloatRaw(MemoryMarshal.Cast<FVector4, float>(Colors));

    /// <summary>Per-vertex colors as pre-packed RGBA8 (0xAABBGGRR). Optional (defaults to white).</summary>
    public void SetColors(ReadOnlySpan<uint> PackedColors)
        => SetColorsPackedRaw(PackedColors);

    /// <summary>Triangle indices (3 per triangle), referencing the vertex streams.</summary>
    public void SetIndices(ReadOnlySpan<int> Indices)
        => SetIndicesRaw(MemoryMarshal.Cast<int, uint>(Indices));

    /// <summary>Triangle indices (3 per triangle), referencing the vertex streams.</summary>
    public void SetIndices(ReadOnlySpan<uint> Indices)
        => SetIndicesRaw(Indices);

    // Flat shims (Runtime module). The component Handle is the first native argument; each span expands to
    // (T*, int). See DotNetDynamicMesh.cpp.

    [NativeCall(Module = "Runtime", EntryPoint = "LuminaSharp_DynMesh_SetPositions")]
    private partial void SetPositionsRaw(ReadOnlySpan<float> Data);

    [NativeCall(Module = "Runtime", EntryPoint = "LuminaSharp_DynMesh_SetNormals")]
    private partial void SetNormalsRaw(ReadOnlySpan<float> Data);

    [NativeCall(Module = "Runtime", EntryPoint = "LuminaSharp_DynMesh_SetUVs")]
    private partial void SetUVsRaw(ReadOnlySpan<float> Data);

    [NativeCall(Module = "Runtime", EntryPoint = "LuminaSharp_DynMesh_SetColorsFloat")]
    private partial void SetColorsFloatRaw(ReadOnlySpan<float> Data);

    [NativeCall(Module = "Runtime", EntryPoint = "LuminaSharp_DynMesh_SetColorsPacked")]
    private partial void SetColorsPackedRaw(ReadOnlySpan<uint> Data);

    [NativeCall(Module = "Runtime", EntryPoint = "LuminaSharp_DynMesh_SetIndices")]
    private partial void SetIndicesRaw(ReadOnlySpan<uint> Data);
}
