-- Premake extension: post-process generated C# csproj XML to add analyzer/source-gen refs, raw SDK props/targets, and blank inherited C++ defines.
-- String post-processing (not premake's internal call-array, which differs across versions).

local p = premake

-- Project-scope fields; values are raw XML lines emitted verbatim.
p.api.register { name = "dotnetrawprops",    scope = "project", kind = "list:string" }  -- into a trailing <PropertyGroup>
p.api.register { name = "dotnetrawitems",    scope = "project", kind = "list:string" }  -- into a trailing <ItemGroup>
p.api.register { name = "dotnetrawtail",     scope = "project", kind = "list:string" }  -- raw XML before </Project>
p.api.register { name = "dotnetstripdefines", scope = "project", kind = "boolean" }     -- blank the inherited C++ defines

require("vstudio")
local dn = p.vstudio.dotnetbase

local function IsManaged(prj)
    return prj.dotnetrawprops or prj.dotnetrawitems or prj.dotnetrawtail or prj.dotnetstripdefines
end

local function EmitDirectoryBuildProps(prj)
    local objdir
    for cfg in p.project.eachconfig(prj) do
        objdir = cfg.objdir
        break
    end
    if not objdir then return end

    -- objdir is <ObjRoot>/<Name>/<Platform>/<Config>; strip platform+config to the per-project base.
    local restoredir = path.join(path.getdirectory(path.getdirectory(objdir)), "restore")
    local rel = path.translate(path.getrelative(prj.location, restoredir), "\\") .. "\\"

    local content = table.concat({
        "<Project>",
        "  <!-- GENERATED by premake (BuildScripts/CSharpProject.lua): route NuGet restore obj into Intermediates. -->",
        "  <PropertyGroup>",
        "    <BaseIntermediateOutputPath>" .. rel .. "</BaseIntermediateOutputPath>",
        "  </PropertyGroup>",
        "</Project>",
        "",
    }, "\n")

    local f = io.open(path.join(prj.location, "Directory.Build.props"), "w")
    if f then
        f:write(content)
        f:close()
    end
end

p.override(dn, "generate", function(base, prj)
    if IsManaged(prj) then
        EmitDirectoryBuildProps(prj)
    end

    local xml = p.capture(function() base(prj) end)

    -- Inherited C++ DefineConstants (e.g. DLL_EXPORT=__declspec(dllexport)) are invalid C#.
    if prj.dotnetstripdefines then
        xml = xml:gsub("(<DefineConstants>).-(</DefineConstants>)", "%1%2")
    end

    local lines = {}
    if prj.dotnetrawprops and #prj.dotnetrawprops > 0 then
        lines[#lines+1] = "  <PropertyGroup>"
        for _, l in ipairs(prj.dotnetrawprops) do lines[#lines+1] = "    " .. l end
        lines[#lines+1] = "  </PropertyGroup>"
    end
    if prj.dotnetrawitems and #prj.dotnetrawitems > 0 then
        lines[#lines+1] = "  <ItemGroup>"
        for _, l in ipairs(prj.dotnetrawitems) do lines[#lines+1] = "    " .. l end
        lines[#lines+1] = "  </ItemGroup>"
    end
    if prj.dotnetrawtail then
        for _, l in ipairs(prj.dotnetrawtail) do lines[#lines+1] = "  " .. l end
    end

    if #lines > 0 then
        local block = table.concat(lines, "\n") .. "\n"
        -- function replacement so '%'/'$' in the block aren't treated as gsub specials.
        xml = xml:gsub("</Project>", function() return block .. "</Project>" end, 1)
    end

    p.outln(xml)
end)
