using System;

namespace LuminaSharp;

/// <summary>
/// The engine-facing call surface: managed -&gt; native. Logging goes through the bootstrap exporter
/// table (a function pointer captured in the default ALC so it survives script reloads); every other
/// entry is a <c>[NativeCall] static partial</c> method whose <c>delegate* unmanaged</c> field, resolve,
/// and marshalling are generated by <c>NativeCallGenerator</c> (defaults: module "LuminaNative", entry
/// "LuminaSharp_{MethodName}"). Pure marshalling mechanics live in <see cref="Interop"/>.
/// </summary>
public static unsafe partial class Native
{
    private static FExporterTable Exports;

    internal static void SetExports(FExporterTable Table)
    {
        Exports = Table;
    }

    public static void Log(ELogLevel Level, string Message)
    {
        if (Exports.Log == null)
        {
            return;
        }

        Span<byte> Scratch = stackalloc byte[1024];
        Interop.FInteropString Encoded = new(Message, Scratch);
        try
        {
            Exports.Log((int)Level, Encoded.Pointer, Encoded.Length);
        }
        finally
        {
            Encoded.Free();
        }
    }

    // Component op-table access. The token returned by FindComponentOps is resolved once per type and
    // reused; the get/has/emplace/remove calls take it plus the world + entity.

    [NativeCall] public static partial IntPtr FindComponentOps(string TypeName);
    [NativeCall] public static partial IntPtr GetComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall] public static partial int HasComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall] public static partial IntPtr EmplaceComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall] public static partial int RemoveComponent(ulong World, uint Entity, IntPtr Ops);

    // Detached construction: a default-constructed, engine-allocated component the C# side owns and
    // frees, plus emplace-by-copy. Backs `new T()` + Registry.Emplace(entity, value).

    [NativeCall] public static partial IntPtr NewComponent(IntPtr Ops);
    [NativeCall] public static partial void DeleteComponent(IntPtr Ops, IntPtr Instance);
    [NativeCall] public static partial IntPtr EmplaceComponentCopy(ulong World, uint Entity, IntPtr Ops, IntPtr Source);

    // Script-to-script: the managed GCHandle (as IntPtr) of the EntityScript bound to an entity, or 0.
    // Resolve with GCHandle.FromIntPtr(...).Target. Backs Registry.GetScript<T>.
    [NativeCall] public static partial IntPtr GetEntityScriptHandle(ulong World, uint Entity);

    // entt::runtime_view iteration for the C# View<...>. Native gathers a CHUNK of entities + parallel
    // component pointers per call (one crossing per chunk). Hand-written delegate* binds: the chunk
    // pointers (uint*, void**) aren't shapes the [NativeCall] generator covers. See DotNetView.cpp.

    public static IntPtr ViewBegin(ulong World, IntPtr* IncludeOps, int NInc, IntPtr* ExcludeOps, int NExc)
    {
        return ViewBegin_(World, IncludeOps, NInc, ExcludeOps, NExc);
    }

    public static int ViewNextChunk(IntPtr State, uint* OutEntities, IntPtr* OutPtrs, int MaxCount, int NInclude)
    {
        return ViewNextChunk_(State, OutEntities, OutPtrs, MaxCount, NInclude);
    }

    public static void ViewEnd(IntPtr State)
    {
        ViewEnd_(State);
    }

    private static readonly delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr> ViewBegin_ =
        (delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewBegin");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int> ViewNextChunk_ =
        (delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewNextChunk");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, void> ViewEnd_ =
        (delegate* unmanaged[Cdecl]<IntPtr, void>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewEnd");

    // Asset loading. String args are UTF-8 encoded by the generated marshalling; the engine VFS resolves
    // the path. Backs the C# Asset API.

    [NativeCall] public static partial IntPtr LoadObject(string Path);
    [NativeCall] public static partial bool AssetExists(string Path);
    [NativeCall] public static partial void LoadObjectAsync(string Path, IntPtr Callback);

    /// <summary>A loaded object's asset path (registry reverse lookup), or "" if it has none. Hand-written:
    /// the native side fills a caller buffer and returns a length, which the [NativeCall] shapes don't cover.</summary>
    public static string GetObjectPath(IntPtr Object)
    {
        if (Object == IntPtr.Zero)
        {
            return string.Empty;
        }

        Span<byte> Buffer = stackalloc byte[1024];
        fixed (byte* Pointer = Buffer)
        {
            int Length = Object_GetPath(Object, Pointer, Buffer.Length);
            if (Length <= 0)
            {
                return string.Empty;
            }
            return Interop.GetString(Pointer, Length < Buffer.Length ? Length : Buffer.Length);
        }
    }

    private static readonly delegate* unmanaged[Cdecl]<IntPtr, byte*, int, int> Object_GetPath =
        (delegate* unmanaged[Cdecl]<IntPtr, byte*, int, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_GetObjectPath");

    // Generic per-property-type accessors. The Reflector emits these for non-blittable properties
    // (FString/FName/object ref) with the property's FProperty* token (Prop) resolved once and cached;
    // C is the container (the live component/object handle). Blittable properties never reach here -- they
    // read/write native memory directly at the property's offset.

    /// <summary>Reads the FString property at the cached token, into a managed string. Two-pass
    /// (length-then-copy), mirroring <see cref="GetObjectPath"/>.</summary>
    public static string PropGetString(IntPtr C, IntPtr Prop)
    {
        return PropGetBuffered(C, Prop, Prop_GetString);
    }

    public static void PropSetString(IntPtr C, IntPtr Prop, string Value)
    {
        PropSetUtf8(C, Prop, Value, Prop_SetString);
    }

    /// <summary>Reads the FName property at the cached token, into a managed string.</summary>
    public static string PropGetName(IntPtr C, IntPtr Prop)
    {
        return PropGetBuffered(C, Prop, Prop_GetName);
    }

    public static void PropSetName(IntPtr C, IntPtr Prop, string Value)
    {
        PropSetUtf8(C, Prop, Value, Prop_SetName);
    }

    [NativeCall] public static partial IntPtr PropGetObject(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetObject(IntPtr C, IntPtr Prop, IntPtr Object);

    // Shared get/set marshalling for the FString/FName accessors (same shape, different native export).
    private static string PropGetBuffered(IntPtr C, IntPtr Prop, delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, int> Get)
    {
        if (C == IntPtr.Zero || Prop == IntPtr.Zero)
        {
            return string.Empty;
        }

        int Length = Get(C, Prop, null, 0);
        if (Length <= 0)
        {
            return string.Empty;
        }

        byte[] Buffer = new byte[Length];
        fixed (byte* Pointer = Buffer)
        {
            int Written = Get(C, Prop, Pointer, Length);
            return Interop.GetString(Pointer, Written < Length ? Written : Length);
        }
    }

    private static void PropSetUtf8(IntPtr C, IntPtr Prop, string Value, delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, void> Set)
    {
        if (C == IntPtr.Zero || Prop == IntPtr.Zero)
        {
            return;
        }

        Span<byte> Scratch = stackalloc byte[256];
        Interop.FInteropString Encoded = new(Value ?? string.Empty, Scratch);
        try
        {
            Set(C, Prop, Encoded.Pointer, Encoded.Length);
        }
        finally
        {
            Encoded.Free();
        }
    }

    private static readonly delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, int> Prop_GetString =
        (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_PropGetString");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, void> Prop_SetString =
        (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, void>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_PropSetString");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, int> Prop_GetName =
        (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_PropGetName");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, void> Prop_SetName =
        (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte*, int, void>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_PropSetName");
}
