using System;

namespace LuminaSharp;

/// <summary>
/// The engine-facing call surface: managed -&gt; native. Logging goes through the bootstrap exporter
/// table (a function pointer captured in the default ALC so it survives script reloads); every other
/// entry is a <c>[NativeCall] static partial</c> method whose <c>delegate* unmanaged</c> field, resolve,
/// and marshalling are generated by <c>NativeCallGenerator</c> (defaults: module "LuminaNative", entry
/// "LuminaSharp_{MethodName}"). Pure marshalling mechanics live in <see cref="Interop"/>.
/// </summary>
public static unsafe partial class Native
{
    private static FExporterTable Exports;

    internal static void SetExports(FExporterTable Table)
    {
        Exports = Table;
    }

    public static void Log(ELogLevel Level, string Message)
    {
        if (Exports.Log == null)
        {
            return;
        }

        Span<byte> Scratch = stackalloc byte[1024];
        Interop.FInteropString Encoded = new(Message, Scratch);
        try
        {
            Exports.Log((int)Level, Encoded.Pointer, Encoded.Length);
        }
        finally
        {
            Encoded.Free();
        }
    }

    // Component op-table access. The token returned by FindComponentOps is resolved once per type and
    // reused; the get/has/emplace/remove calls take it plus the world + entity.

    [NativeCall] public static partial IntPtr FindComponentOps(string TypeName);
    // Pure reads (try_get / any_of): non-blocking, no managed re-entry -> SuppressGCTransition.
    [NativeCall(SuppressGCTransition = true)] public static partial IntPtr GetComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall(SuppressGCTransition = true)] public static partial int HasComponent(ulong World, uint Entity, IntPtr Ops);
    // Emplace/Remove fire on_construct/on_destroy, which can re-enter managed (signal trampolines) -> not safe.
    [NativeCall] public static partial IntPtr EmplaceComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall] public static partial int RemoveComponent(ulong World, uint Entity, IntPtr Ops);

    // Detached construction: a default-constructed, engine-allocated component the C# side owns and
    // frees, plus emplace-by-copy. Backs `new T()` + Registry.Emplace(entity, value).

    [NativeCall] public static partial IntPtr NewComponent(IntPtr Ops);
    [NativeCall] public static partial void DeleteComponent(IntPtr Ops, IntPtr Instance);
    [NativeCall] public static partial IntPtr EmplaceComponentCopy(ulong World, uint Entity, IntPtr Ops, IntPtr Source);

    // Registry signals. Connect binds a managed thunk (+ GCHandle context) to a component's
    // on_construct/on_destroy/on_update sink and returns an opaque subscription handle; Disconnect releases
    // it. Patch fires on_update for an entity's component (the manual signal pulse). Kind: 0/1/2.

    [NativeCall] public static partial IntPtr RegistryConnect(ulong World, IntPtr Ops, int Kind, IntPtr Thunk, IntPtr Context);
    [NativeCall] public static partial void RegistryDisconnect(ulong World, IntPtr Ops, int Kind, IntPtr Handle);
    [NativeCall] public static partial void RegistryPatch(ulong World, uint Entity, IntPtr Ops);

    // Script-to-script: the managed GCHandle (as IntPtr) of the EntityScript bound to an entity, or 0.
    // Resolve with GCHandle.FromIntPtr(...).Target. Backs Registry.GetScript<T>.
    [NativeCall] public static partial IntPtr GetEntityScriptHandle(ulong World, uint Entity);

    // entt::runtime_view iteration for the C# View<...>. Native gathers a CHUNK of entities + parallel
    // component pointers per call (one crossing per chunk). Hand-written delegate* binds: the chunk
    // pointers (uint*, void**) aren't shapes the [NativeCall] generator covers. See DotNetView.cpp.

    public static IntPtr ViewBegin(ulong World, IntPtr* IncludeOps, int NInc, IntPtr* ExcludeOps, int NExc)
    {
        return ViewBegin_(World, IncludeOps, NInc, ExcludeOps, NExc);
    }

    public static int ViewNextChunk(IntPtr State, uint* OutEntities, IntPtr* OutPtrs, int MaxCount, int NInclude)
    {
        return ViewNextChunk_(State, OutEntities, OutPtrs, MaxCount, NInclude);
    }

    public static void ViewEnd(IntPtr State)
    {
        ViewEnd_(State);
    }

    private static readonly delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr> ViewBegin_ =
        (delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewBegin");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int> ViewNextChunk_ =
        (delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewNextChunk");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, void> ViewEnd_ =
        (delegate* unmanaged[Cdecl]<IntPtr, void>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewEnd");

    // Asset loading. String args are UTF-8 encoded by the generated marshalling; the engine VFS resolves
    // the path. Backs the C# Asset API.

    [NativeCall] public static partial IntPtr LoadObject(string Path);
    [NativeCall] public static partial bool AssetExists(string Path);
    [NativeCall] public static partial void LoadObjectAsync(string Path, IntPtr Callback);

    /// <summary>A loaded object's asset path (registry reverse lookup), or "" if it has none.</summary>
    [NativeCall] public static partial string GetObjectPath(IntPtr Object);

    // Generic per-property-type accessors. The Reflector emits these for non-blittable properties
    // (FString/FName/object ref) with the property's FProperty* token (Prop) resolved once and cached;
    // C is the container (the live component/object handle). Blittable properties never reach here -- they
    // read/write native memory directly at the property's offset.

    // String get = generated two-pass buffer ABI; string set / object ref = generated string/pointer args.

    [NativeCall] public static partial string PropGetString(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetString(IntPtr C, IntPtr Prop, string Value);
    [NativeCall] public static partial string PropGetName(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetName(IntPtr C, IntPtr Prop, string Value);
    [NativeCall] public static partial IntPtr PropGetObject(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetObject(IntPtr C, IntPtr Prop, IntPtr Object);
}
